language: minimal

# Define the build stages
stages:
  - terraform

# Configure the AWS credentials
env:
  global:
    - AWS_REGION=ap-southeast-2

# Install dependencies and configure AWS CLI
install:
  - curl -sSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - sudo apt-get update && sudo apt-get install terraform -y
  - sudo apt-get install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_REGION

# Terraform stages
jobs:
  include:
    - stage: terraform
      name: "Terraform Plan"
      script:
        - terraform init
        - terraform validate
        - terraform plan -out=tfplan
        # - terraform apply -auto-approve
        # - terraform destroy -auto-approve
